"""
Integration tests for the /api/v1/generate and /api/v1/download endpoints.

Uses a stub LLM client so that no real SAI Library or OpenAI key is needed.
"""

from __future__ import annotations

import zipfile
import io

import pytest
import pytest_asyncio
from fastapi.testclient import TestClient

from app.main import app
from app.models.schemas import AgentTarget, ConnectorType
from app.routers.generate import _llm_client
from app.services.llm import LLMClient


# ---------------------------------------------------------------------------
# Stub LLM client
# ---------------------------------------------------------------------------


class StubLLMClient:
    """Returns a fixed string; no network calls."""

    async def complete(self, system_prompt: str, user_prompt: str) -> str:
        return "# Stub Skill\n\nThis is a test artifact generated by the stub LLM."


def _stub_llm() -> LLMClient:
    return StubLLMClient()  # type: ignore[return-value]


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def client() -> TestClient:
    app.dependency_overrides[_llm_client] = _stub_llm
    yield TestClient(app)
    app.dependency_overrides.clear()


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


def test_health(client: TestClient) -> None:
    resp = client.get("/health")
    assert resp.status_code == 200
    data = resp.json()
    assert data["status"] == "ok"


def test_list_agents(client: TestClient) -> None:
    resp = client.get("/api/v1/agents")
    assert resp.status_code == 200
    agents = resp.json()
    ids = {a["id"] for a in agents}
    assert "claude" in ids
    assert "copilot" in ids
    assert "cursor" in ids
    assert "vertex_ai" in ids
    assert "windsurf" in ids
    assert "generic_openai" in ids


def test_generate_claude(client: TestClient) -> None:
    payload = {
        "agent_target": "claude",
        "high_level_description": (
            "Skill to review Node.js backend pull requests following "
            "Stefanini internal coding standards."
        ),
        "context_materials": [
            {
                "connector_type": "rest_api",
                "connection_metadata": {
                    "host": "https://api.example.com",
                    "api_key_env_ref": "$env:MY_API_KEY",
                },
                "description": (
                    "Company REST API – the agent should understand the available "
                    "endpoints and expected request/response shapes."
                ),
            }
        ],
    }
    resp = client.post("/api/v1/generate", json=payload)
    assert resp.status_code == 200
    data = resp.json()
    assert "artifacts" in data
    assert "suggested_prompt" in data
    assert "download_token" in data

    paths = [a["path"] for a in data["artifacts"]]
    assert "SKILL.md" in paths
    assert "README.md" in paths


def test_generate_cursor(client: TestClient) -> None:
    payload = {
        "agent_target": "cursor",
        "high_level_description": (
            "Skill for Python data-pipeline development with strict type hints "
            "and mypy compliance."
        ),
        "context_materials": [],
    }
    resp = client.post("/api/v1/generate", json=payload)
    assert resp.status_code == 200
    paths = [a["path"] for a in resp.json()["artifacts"]]
    assert ".cursorrules" in paths


def test_generate_copilot(client: TestClient) -> None:
    payload = {
        "agent_target": "copilot",
        "high_level_description": (
            "Skill for reviewing TypeScript React components for accessibility "
            "and performance best practices."
        ),
        "context_materials": [],
    }
    resp = client.post("/api/v1/generate", json=payload)
    assert resp.status_code == 200
    paths = [a["path"] for a in resp.json()["artifacts"]]
    assert ".github/copilot-instructions.md" in paths


def test_generate_vertex_ai(client: TestClient) -> None:
    payload = {
        "agent_target": "vertex_ai",
        "high_level_description": "Skill for answering questions about Stefanini HR policies.",
        "context_materials": [],
    }
    resp = client.post("/api/v1/generate", json=payload)
    assert resp.status_code == 200
    paths = [a["path"] for a in resp.json()["artifacts"]]
    assert "system_instruction.txt" in paths


def test_generate_windsurf(client: TestClient) -> None:
    payload = {
        "agent_target": "windsurf",
        "high_level_description": (
            "Skill for Go microservice development with OpenTelemetry tracing."
        ),
        "context_materials": [],
    }
    resp = client.post("/api/v1/generate", json=payload)
    assert resp.status_code == 200
    paths = [a["path"] for a in resp.json()["artifacts"]]
    assert ".windsurfrules" in paths


def test_download_zip(client: TestClient) -> None:
    payload = {
        "agent_target": "claude",
        "high_level_description": "Skill to summarise meeting notes for project managers.",
        "context_materials": [],
    }
    gen_resp = client.post("/api/v1/generate", json=payload)
    token = gen_resp.json()["download_token"]

    dl_resp = client.get(f"/api/v1/download/{token}")
    assert dl_resp.status_code == 200
    assert dl_resp.headers["content-type"] == "application/zip"

    zf = zipfile.ZipFile(io.BytesIO(dl_resp.content))
    names = zf.namelist()
    assert "SKILL.md" in names
    assert "README.md" in names


def test_download_invalid_token(client: TestClient) -> None:
    resp = client.get("/api/v1/download/not-a-valid-token")
    assert resp.status_code == 404


def test_generate_rejects_plaintext_password(client: TestClient) -> None:
    """Passwords supplied as plain text must be rejected with 422."""
    payload = {
        "agent_target": "claude",
        "high_level_description": "Skill that reads from a Postgres database.",
        "context_materials": [
            {
                "connector_type": "postgres",
                "connection_metadata": {
                    "host": "db.example.com",
                    "port": 5432,
                    "database": "mydb",
                    "username": "admin",
                    "password_env_ref": "plaintext_password_not_allowed",
                },
                "description": (
                    "Postgres DB with order data – agent must understand the schema."
                ),
            }
        ],
    }
    resp = client.post("/api/v1/generate", json=payload)
    assert resp.status_code == 422


def test_generate_missing_description(client: TestClient) -> None:
    """Requests without a high_level_description must be rejected with 422."""
    payload = {
        "agent_target": "claude",
        "context_materials": [],
    }
    resp = client.post("/api/v1/generate", json=payload)
    assert resp.status_code == 422


def test_generate_short_description(client: TestClient) -> None:
    """high_level_description shorter than 20 chars must be rejected."""
    payload = {
        "agent_target": "claude",
        "high_level_description": "Too short",
        "context_materials": [],
    }
    resp = client.post("/api/v1/generate", json=payload)
    assert resp.status_code == 422
